### ISSUE TITLE
HTML tag brackets colour vs tag name colour

### ISSUE THREAD

**Issue by drootz** [rockymadden/tomorrow-night-eighties-syntax-theme#25]
The opening and closing brackets of HTML tags is different from the tag name colour. Not sure if this is intentional or not...

Adding this css in `styles/html.less` would "fix" the colour behaviour.

```css
.html {
  .punctuation.definition.tag {
    color: @red;
  }
}
```

I forked your package to add this css. Let me know if you fix this so I can drop my fork. :)

Cheers! Thanks for the Angular syntax on this theme!
